project:
  type: website

execute:
  freeze: auto

website:
  title: "CancerDataSci"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seandavi/
format:
  html:
    theme: united
    css: styles.css



